version: "3.9"

services:
  api:
    build: .
    # command: daphne config.asgi:application --port 8000 --bind 0.0.0.0
    restart: always
    ports:
      - 8009:8000
    env_file:
      - .env.production
    volumes:
      - .:/app
      - /var/www/mcb/staticfiles:/app/staticfiles
    networks:
      - mcb-network

  # redis:
  #   image: redis:latest
  #   restart: "on-failure"
  #   ports:
  #     - 6380:6379
  #   networks:
  #     - mcb-network

networks:
  mcb-network:

